version: '3.8'

volumes:
  pg_data:
    driver: local
  redis:
    driver: local

x-base: &base-backend
  environment:
    DATABASE_URL: postgres://db_user:db_password@db:5432/db_name
    REDIS_URL: redis://redis:6379
    DEBUG: "on"
    ENVIRONMENT: development
    ALLOWED_HOSTS: localhost,0.0.0.0
  volumes:
    - .:/code:delegated
  depends_on:
    - db
    - redis

services:
  redis:
    image: library/redis:6.0
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  db:
    image: library/postgres:13
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"

  backend:
    <<: *base-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    ports:
      - "8002:8002"
